### ISSUE TITLE
Build-Error, when using docker-compose

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/mqtt-proxy#6]
Hi, 

when using docker-compose -f docker-compose.yml up I do get the following error:

```
......
Step 5/16 : RUN make deps-install
 ---> Running in 25aeea02885e
fatal: not a git repository (or any of the parent directories): .git
go get -v $(cat .deps)
: invalid github.com/ import path "github.com/eclipse/paho.mqtt.golang/packets\r"
: invalid github.com/ import path "github.com/gorilla/websocket\r"
: invalid github.com/ import path "github.com/namsral/flag\r"
: invalid github.com/ import path "github.com/satori/go.uuid\r"
: invalid github.com/ import path "github.com/sirupsen/logrus\r"
: invalid github.com/ import path "github.com/x-cray/logrus-prefixed-formatter\r"
make: *** [Makefile:43: deps-install] Error 1
ERROR: Service 'mqtt-proxy' failed to build: The command '/bin/sh -c make deps-install' returned a non-zero code: 2
```

Any idea? Please let me know, if you need any specific information from me.

Thanks,
Chris

**Comment by jdavanne** [comment]
Did you do git clone on windows ?

**Comment by cwiechmann** [comment]
I tried it first on Linux and then on Windows. Same error occurs on both platforms.

**Comment by jdavanne** [comment]
Well, on Linux, was it the same error ? If not, it should be now fixed....

**Comment by cwiechmann** [comment]
Thanks for your help! Problem was caused, by a file-conversion from Unix2Dos for the .deps file, which was causing the make error.
Send a pull-request that adds a dos2unix to the Dockerfile to stabilize the build process.
`RUN dos2unix .deps `
